{{- if and .Values.postgres.enabled .Values.postgres.persistence.enabled }}
{{- if eq .Values.postgres.persistence.storageClass "manual" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "backstage.fullname" . }}-postgres-pv
spec:
  capacity:
    storage: {{ .Values.postgres.persistence.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "backstage.fullname" . }}-postgres-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  {{- if .Values.postgres.persistence.storageClass }}
  storageClassName: {{ .Values.postgres.persistence.storageClass | quote }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.storage }}
{{- end }}
