{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backstage.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "backstage.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "backstage.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-postgres-secrets
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
              subPath: data
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: {{ include "backstage.fullname" . }}-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  selector:
    app: {{ include "backstage.fullname" . }}-postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: 5432
{{- end }}
