app:
  baseUrl: https://backstage.tyagi.fun

backend:
  baseUrl: https://backstage.tyagi.fun
  listen:
    port: 7007
    host: 0.0.0.0
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    upgrade-insecure-requests: false

  cors:
    origin: https://backstage.tyagi.fun
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

  auth:
    dangerouslyDisableDefaultAuthPolicy: true
    keys:
      - secret: ${BACKEND_SECRET}

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DATABASE}
      ssl: false

# Production Authentication Configuration
auth:
  providers:
    guest:
      dangerouslyAllow: true

catalog:
  locations:
    - type: file
      target: ./examples/entities.yaml
    - type: file
      target: ./examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./examples/org.yaml
      rules:
        - allow: [User, Group]
